# Generated by Django 3.2.6 on 2021-09-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='nome',
        ),
    ]
