# Generated by Django 3.2.6 on 2021-10-01 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0007_remove_questionario_aluno'),
        ('inscricao', '0002_auto_20211001_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='questionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='questionario.questionario'),
            preserve_default=False,
        ),
    ]
