# Generated by Django 3.2.6 on 2021-09-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_situacao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='situacao',
            options={'verbose_name': 'Situação', 'verbose_name_plural': 'Situações'},
        ),
    ]
