# Generated by Django 3.2.6 on 2021-10-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0003_inscricao_questionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='inscricao_situacao',
            field=models.IntegerField(choices=[(1, 'Inscrição realizada'), (2, 'Realizar correção'), (3, 'Inscrição deferida'), (4, 'Inscrição indeferida')], default=1),
        ),
    ]
