# Generated by Django 3.2.6 on 2021-10-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0004_alter_inscricao_inscricao_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='inscricao_dta_fim_correcao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data para correção'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='inscricao_dta_ini_correcao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data para correção'),
        ),
    ]
