# Generated by Django 3.2.6 on 2021-09-02 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0026_alter_alunoanexo_aluno_anexo_arq'),
        ('inscricao', '0005_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='aluno',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
            preserve_default=False,
        ),
    ]
