# Generated by Django 3.2.6 on 2021-10-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0005_auto_20211017_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='inscricao_dta_fim_correcao',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='inscricao_dta_ini_correcao',
        ),
    ]
