# Generated by Django 3.2.6 on 2021-10-27 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_curso_curso_tipo'),
        ('inscricao', '0007_alter_inscricao_inscricao_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='curso.semestre'),
            preserve_default=False,
        ),
    ]
