# Generated by Django 3.2.6 on 2021-09-02 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0027_auto_20210902_1105'),
        ('inscricao', '0008_remove_inscricao_edital'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='edital',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='edital.edital'),
            preserve_default=False,
        ),
    ]
