# Generated by Django 3.2.6 on 2021-09-02 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_inscricao_edital'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='modalidade',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='inscricao.modalidade'),
            preserve_default=False,
        ),
    ]
