# Generated by Django 3.2.6 on 2021-10-27 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0009_auto_20211027_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscricao',
            name='questionario',
        ),
    ]
