# Generated by Django 3.2.6 on 2021-10-27 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0010_remove_inscricao_questionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionarioAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('quest_aluno_anexo_tipo', models.IntegerField(choices=[(1, 'Valor Gasto com Van'), (2, 'Valor Gasto com Aluguel ou Financiamento do Imovel'), (3, 'Valor Gasto com Energia'), (4, 'Valor Gasto com Água'), (5, 'Valor Gasto com Conomínio'), (6, 'Valor Gasto com Medicação')], verbose_name='Inclua os anexos das suas despesas')),
                ('quest_aluno_anexo_valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Informe o valor do anexo')),
                ('quest_aluno_anexo_arq', models.FileField(upload_to='media/questionario', verbose_name='Anexo/Comprovante')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inscricao.inscricao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
