# Generated by Django 3.2.6 on 2021-09-02 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20210901_1300'),
        ('inscricao', '0010_inscricao_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
            preserve_default=False,
        ),
    ]
