# Generated by Django 3.2.6 on 2021-10-27 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0011_questionarioanexo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscricao',
            old_name='semestre',
            new_name='semestre_aluno',
        ),
    ]
