# Generated by Django 3.2.6 on 2021-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0012_remove_inscricao_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='situacao',
            name='situacao_status',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='situacao',
            field=models.ManyToManyField(to='inscricao.Situacao'),
        ),
    ]
