# Generated by Django 3.2.6 on 2021-10-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0012_rename_semestre_inscricao_semestre_aluno'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuestionarioAnexo',
            new_name='InscriçãoQuestionarioAnexo',
        ),
    ]
