# Generated by Django 3.2.6 on 2021-09-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0014_remove_inscricao_situacao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Situacao',
        ),
    ]
