# Generated by Django 3.2.6 on 2021-09-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0015_delete_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='inscricao_situacao',
            field=models.CharField(choices=[(1, 'inscrição realizada'), (2, 'realizar correção'), (3, 'inscrição deferida'), (4, 'inscrição indeferida')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='situacao_obs',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Observação da inscrição'),
        ),
    ]
