# Generated by Django 3.2.6 on 2021-09-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0016_auto_20210902_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='inscricao_situacao',
            field=models.IntegerField(choices=[(1, 'inscrição realizada'), (2, 'realizar correção'), (3, 'inscrição deferida'), (4, 'inscrição indeferida')]),
        ),
    ]
