# Generated by Django 3.2.6 on 2021-09-02 17:47

from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('banco_status', models.BooleanField(default=True, verbose_name='Banco ativo?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('cidade_status', models.BooleanField(default=True, verbose_name='Cidade ativa?')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('genero', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('P', 'Prefiro não informar')], max_length=1, verbose_name='Sexo')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data de nascimento')),
                ('foto', stdimage.models.StdImageField(blank=True, null=True, upload_to='pessoa', verbose_name='Image')),
                ('email', models.EmailField(max_length=200, verbose_name='E-mail')),
                ('cep', models.CharField(max_length=15, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('bairro', models.CharField(max_length=50, verbose_name='Bairro')),
                ('tel_celular', models.CharField(max_length=15, verbose_name='Nº do Celular')),
                ('tel_telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Telefone')),
                ('tel_responsavel', models.CharField(max_length=15, verbose_name='Nº do Reponsável')),
                ('possui_conta', models.BooleanField(default=True, verbose_name='Possui conta?')),
                ('tipo_conta', models.CharField(choices=[('CP', 'Conta Poupança'), ('CC', 'Conta Corrente'), ('PP', 'Conta Poupex'), ('PO', 'Conta Poupança Ouro'), ('CU', 'Conta Universitária'), ('CL', 'Conta Salário')], max_length=2, verbose_name='Tipo de conta')),
                ('agencia', models.CharField(max_length=20, verbose_name='N° da Agência')),
                ('conta', models.CharField(max_length=20, verbose_name='N° da Conta')),
                ('nome_pai', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai')),
                ('escolaridade_pai', models.IntegerField(blank=True, choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação'), (8, 'Mestrado'), (9, 'Doutorado')], null=True, verbose_name='Escolaridade do Pai')),
                ('nome_mae', models.CharField(max_length=100, verbose_name='Nome da Mãe')),
                ('escolaridade_mae', models.IntegerField(choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação'), (8, 'Mestrado'), (9, 'Doutorado')], verbose_name='Escolaridade da Mãe')),
                ('pessoa_status', models.BooleanField(default=True, verbose_name='Pessoa ativa?')),
                ('banco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.banco')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.cidade')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
    ]
