# Generated by Django 3.2.6 on 2021-08-31 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matricula')),
                ('status_aluno', models.BooleanField(default=True, verbose_name='Aluno ativo? ')),
            ],
        ),
    ]
