# Generated by Django 3.2.6 on 2021-10-06 13:40

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='media/media_pessoa', verbose_name='Image'),
        ),
    ]
