# Generated by Django 3.2.6 on 2021-08-31 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='pessoa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa'),
        ),
    ]
