# Generated by Django 3.2.6 on 2021-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pessoa_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pessoa_revisar_cadastro',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Forçar o Pessoa Revisar cadastro?'),
        ),
    ]
