# Generated by Django 3.2.6 on 2021-09-01 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210831_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
