# Generated by Django 3.2.6 on 2021-09-01 23:52

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(null=True, upload_to='pessoa', verbose_name='Imagem'),
        ),
    ]
