# Generated by Django 3.2.6 on 2021-09-02 00:08

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pessoa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(default='a', upload_to='pessoa', verbose_name='Imagem'),
            preserve_default=False,
        ),
    ]
