# Generated by Django 3.2.6 on 2021-09-02 00:09

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_pessoa_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='pessoa', verbose_name='Imagem'),
        ),
    ]
