# Generated by Django 3.2.6 on 2021-09-02 00:58

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pessoa_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pessoa',
            options={'verbose_name': 'Pessoa', 'verbose_name_plural': 'Pessoas'},
        ),
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(default='centro', max_length=50, verbose_name='Bairro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(default='78110044', max_length=15, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default=1, max_length=11, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(default='a@gmail.com', max_length=200, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='endereco',
            field=models.CharField(default='endereco', max_length=100, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='genero',
            field=models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('P', 'Prefiro não informar')], default='F', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='rg',
            field=models.CharField(default=1, max_length=15, verbose_name='RG'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tel_celular',
            field=models.CharField(default=1, max_length=15, verbose_name='Nº do Celular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tel_telefone',
            field=models.CharField(default=1, max_length=15, verbose_name='N° de Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='pessoa', verbose_name='Image'),
        ),
    ]
