# Generated by Django 3.2.6 on 2021-09-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210901_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tel_responsavel',
            field=models.CharField(default='1', max_length=15, verbose_name='Nº do Reponsável'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tel_telefone',
            field=models.CharField(max_length=15, null=True, verbose_name='N° de Telefone'),
        ),
    ]
