# Generated by Django 3.2.6 on 2021-09-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210901_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='tel_telefone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='N° de Telefone'),
        ),
    ]
