# Generated by Django 3.2.6 on 2021-09-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pessoa_tel_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='agencia',
            field=models.CharField(default='1', max_length=20, verbose_name='N° da Agência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='conta',
            field=models.CharField(default='2', max_length=20, verbose_name='N° da Conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade_mae',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação'), (8, 'Mestrado'), (9, 'Doutorado')], default=1, verbose_name='Escolaridade da Mãe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='escolaridade_pai',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação'), (8, 'Mestrado'), (9, 'Doutorado')], default=1, verbose_name='Escolaridade do Pai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_mae',
            field=models.CharField(default='mae', max_length=100, verbose_name='Nome da Mãe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='possui_conta',
            field=models.BooleanField(default=True, verbose_name='Possui conta?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo_conta',
            field=models.CharField(choices=[('CP', 'Conta Poupança'), ('CC', 'Conta Corrente'), ('PP', 'Conta Poupex'), ('PO', 'Conta Poupança Ouro'), ('CU', 'Conta Universitária'), ('CL', 'Conta Salário')], default='CC', max_length=2, verbose_name='Tipo de conta'),
            preserve_default=False,
        ),
    ]
