# Generated by Django 3.2.6 on 2021-09-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('quest_aluno_form_ingre', models.CharField(choices=[('A', 'Por Ampla Concorrência'), ('C', 'Por Meio de Cota')], max_length=1, verbose_name='Forma de Ingresso')),
                ('quest_aluno_dist_escola', models.IntegerField(choices=[(1, 'Aproximadamente 1km'), (2, 'Aproximadamente 2.5km'), (3, 'Aproximadamente 5km'), (4, 'Aproximadamente 7.5km'), (5, 'Aproximadamente 10km'), (6, 'Aproximadamente 12.5km'), (7, 'Aproximadamente 15km'), (8, 'Aproximadamente 17.5km'), (9, 'Aproximadamente 20km'), (10, 'Aproximadamente 30km'), (11, 'Acima de 30km')], verbose_name='Distância aproximada da residência ao Campus em KM?')),
                ('quest_aluno_transporte', models.IntegerField(choices=[(1, 'Transporte Coletivo'), (2, 'Van'), (3, 'Carro'), (4, 'Moto'), (5, 'A pé'), (6, 'Carona'), (7, 'Bicicleta')], verbose_name='Informe o meio de transporte utilizado para chegar ao Campus?')),
                ('quest_aluno_tempo_escola', models.IntegerField(choices=[(1, 'Aproximadamente 5 minutos'), (2, 'Aproximadamente 10 minutos'), (3, 'Aproximadamente 15 minutos'), (4, 'Aproximadamente 20 minutos'), (5, 'Aproximadamente 25 minutos'), (6, 'Aproximadamente 30 minutos'), (7, 'Aproximadamente 45 minutos'), (8, 'Aproximadamente 1 hora'), (9, 'Aproximadamente 1 hora e 30 minutos'), (10, 'Aproximadamente 2 horas'), (11, 'Acima de 2 horas')], verbose_name='Tempo que o (a) estudante gasta da sua residência ao Campus')),
                ('quest_aluno_gestante', models.BooleanField(default=False, verbose_name='Aluna está Gestante? ')),
                ('quest_aluno_lactante', models.BooleanField(default=False, verbose_name='Você é Lactante? ')),
                ('quest_aluno_medicacao', models.BooleanField(default=False, verbose_name='Medicamentos de Uso Regular?')),
                ('quest_aluno_medicacao_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Informe a medicação')),
                ('quest_aluno_medicacao_cid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Informe o CID (Classificação Internacional de Doenças)')),
            ],
            options={
                'verbose_name': 'Questionário',
                'verbose_name_plural': 'Questionários',
            },
        ),
    ]
