# Generated by Django 3.2.6 on 2021-09-08 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0010_delete_alunoanexo'),
        ('edital', '0014_auto_20210907_2050'),
        ('questionario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionario',
            name='aluno',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionario',
            name='edital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edital.edital'),
            preserve_default=False,
        ),
    ]
