# Generated by Django 3.2.6 on 2021-10-01 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0005_auto_20211001_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionario',
            name='edital',
        ),
    ]
