# Generated by Django 3.2.6 on 2021-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0008_auto_20211001_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioanexo',
            name='quest_aluno_anexo_arq',
            field=models.FileField(upload_to='media/questionario', verbose_name='Anexo/Comprovante'),
        ),
    ]
