# Generated by Django 3.2.6 on 2021-10-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0009_alter_questionarioanexo_quest_aluno_anexo_arq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionarioanexo',
            name='questionario',
        ),
    ]
