# Generated by Django 3.2.6 on 2021-10-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionario', '0010_remove_questionarioanexo_questionario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questionario',
        ),
    ]
