# Generated by Django 3.2.6 on 2021-09-10 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='usuario_login',
            new_name='usuario_matricula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='aluno',
        ),
    ]
