# Generated by Django 3.2.6 on 2021-09-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20210910_1231'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
