# Generated by Django 3.2.6 on 2021-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Processado com sucesso'), (2, 'Não Processado'), (3, 'Erro ao realizar processamentos, verifique o padrão do arquivo!')], default=1, verbose_name='Tipo do Curso'),
            preserve_default=False,
        ),
    ]
