# Generated by Django 3.2.6 on 2021-10-08 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0002_importacao_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Arquivo Processado com sucesso'), (2, 'Arquivo não Processado'), (3, 'Erro ao realizar processamentos, verifique o padrão do arquivo!')], default=2, verbose_name='Tipo do Curso'),
        ),
    ]
