# Generated by Django 3.2.6 on 2021-10-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0003_alter_importacao_situacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='ano',
            field=models.IntegerField(default=2021, verbose_name='Ano:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='importacao',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre')], default=2, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
