# Generated by Django 3.2.6 on 2021-10-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacao', '0004_auto_20211008_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='resultado',
            field=models.FileField(blank=True, null=True, upload_to='xlsx_resultado'),
        ),
    ]
