# Generated by Django 3.2.6 on 2021-09-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_status', models.BooleanField(default=True, verbose_name='Aluno ativo? ')),
                ('aluno_matricula', models.BigIntegerField(unique=True, verbose_name='Matricula')),
                ('aluno_form_ingre', models.CharField(choices=[('A', 'Por Ampla Concorrência'), ('C', 'Por Meio de Cota')], max_length=1, verbose_name='Forma de Ingresso')),
                ('aluno_dist_escola', models.IntegerField(choices=[(1, 'Aproximadamente 1km'), (2, 'Aproximadamente 2.5km'), (3, 'Aproximadamente 5km'), (4, 'Aproximadamente 7.5km'), (5, 'Aproximadamente 10km'), (6, 'Aproximadamente 12.5km'), (7, 'Aproximadamente 15km'), (8, 'Aproximadamente 17.5km'), (9, 'Aproximadamente 20km'), (10, 'Aproximadamente 30km'), (11, 'Acima de 30km')], verbose_name='Distância aproximada da residência ao Campus em KM?')),
                ('aluno_transporte', models.IntegerField(choices=[(1, 'Transporte Coletivo'), (2, 'Van'), (3, 'Carro'), (4, 'Moto'), (5, 'A pé'), (6, 'Carona'), (7, 'Bicicleta')], verbose_name='Informe o meio de transporte utilizado para chegar ao Campus?')),
                ('aluno_tempo_escola', models.IntegerField(choices=[(1, 'Aproximadamente 5 minutos'), (2, 'Aproximadamente 10 minutos'), (3, 'Aproximadamente 15 minutos'), (4, 'Aproximadamente 20 minutos'), (5, 'Aproximadamente 25 minutos'), (6, 'Aproximadamente 30 minutos'), (7, 'Aproximadamente 45 minutos'), (8, 'Aproximadamente 1 hora'), (9, 'Aproximadamente 1 hora e 30 minutos'), (10, 'Aproximadamente 2 horas'), (11, 'Acima de 2 horas')], verbose_name='Tempo que o (a) estudante gasta da sua residência ao Campus')),
                ('aluno_gestante', models.BooleanField(default=False, verbose_name='Aluna está Gestante? ')),
                ('aluno_lactante', models.BooleanField(default=False, verbose_name='Você é Lactante? ')),
                ('aluno_medicacao', models.BooleanField(default=False, verbose_name='Medicamentos de Uso Regular?')),
                ('aluno_medicacao_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Informe a medicação')),
                ('aluno_medicacao_cid', models.CharField(blank=True, max_length=100, null=True, verbose_name='Informe o CID (Classificação Internacional de Doenças)')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='curso.curso')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoa')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='curso.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='AlunoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('aluno_anexo_tipo', models.IntegerField(choices=[(1, 'Valor Gasto com Van'), (2, 'Valor Gasto com Aluguel ou Financiamento do Imovel'), (3, 'Valor Gasto com Energia'), (4, 'Valor Gasto com Água'), (5, 'Valor Gasto com Conomínio'), (6, 'Valor Gasto com Medicação')], verbose_name='Inclua os anexos das suas despesas')),
                ('aluno_anexo_valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Informe o valor do anexo')),
                ('aluno_anexo_arq', models.CharField(max_length=100, verbose_name='Anexo/Comprovante')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aluno.aluno')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
