# Generated by Django 3.2.6 on 2021-09-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_form_ingre',
            field=models.CharField(choices=[('A', 'Por Ampla Concorrência'), ('C', 'Por Meio de Cota')], max_length=20, verbose_name='Forma de Ingresso'),
        ),
    ]
