# Generated by Django 3.2.6 on 2021-09-01 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cruso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.curso'),
        ),
    ]
