# Generated by Django 3.2.6 on 2021-09-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_aluno_cruso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='cruso',
            new_name='curso',
        ),
    ]
