# Generated by Django 3.2.6 on 2021-09-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20210901_1236'),
        ('aluno', '0003_rename_cruso_aluno_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='curso.curso'),
        ),
    ]
