# Generated by Django 3.2.6 on 2021-09-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_modalidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='modalidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='aluno.modalidade'),
        ),
    ]
