# Generated by Django 3.2.6 on 2021-09-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0005_alter_aluno_aluno_dist_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_form_ingre',
            field=models.IntegerField(choices=[(1, 'Por Ampla Concorrência'), (2, 'Por Meio de Cota')], verbose_name='Forma de Ingresso'),
        ),
    ]
