# Generated by Django 3.2.6 on 2021-09-01 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0006_aluno_modalidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='modalidade',
        ),
    ]
