# Generated by Django 3.2.6 on 2021-09-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0007_remove_aluno_modalidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='matricula',
            new_name='aluno_matricula',
        ),
    ]
