# Generated by Django 3.2.6 on 2021-09-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_alunoanexo_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_dist_escola',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_form_ingre',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_gestante',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_lactante',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_medicacao',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_medicacao_cid',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_medicacao_desc',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_tempo_escola',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_transporte',
        ),
    ]
