# Generated by Django 3.2.6 on 2021-09-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0008_rename_matricula_aluno_aluno_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_form_ingre',
            field=models.CharField(choices=[('A', 'Por Ampla Concorrência'), ('C', 'Por Meio de Cota')], default='A', max_length=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
