# Generated by Django 3.2.6 on 2021-09-08 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_auto_20210907_2118'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlunoAnexo',
        ),
    ]
