# Generated by Django 3.2.6 on 2021-09-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0009_aluno_aluno_form_ingre'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_agencia',
            field=models.CharField(default='1', max_length=20, verbose_name='N° da Agência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_conta',
            field=models.CharField(default='1', max_length=20, verbose_name='N° da Conta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_nome_pai_asdasda_sadasdasdas_asudhaudhuashdusa',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_possui_conta',
            field=models.BooleanField(default=True, verbose_name='Possui conta?'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_tipo_conta',
            field=models.CharField(choices=[('CP', 'Conta Poupança'), ('CC', 'Conta Corrente'), ('PP', 'Conta Poupex'), ('PO', 'Conta Poupança Ouro'), ('CU', 'Conta Universitária'), ('CL', 'Conta Salário')], default='CC', max_length=2, verbose_name='Tipo de conta'),
            preserve_default=False,
        ),
    ]
