# Generated by Django 3.2.6 on 2021-09-10 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aluno', '0010_delete_alunoanexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='AltPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AltPor_usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='IncPor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='IncPor_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
