# Generated by Django 3.2.6 on 2021-09-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_auto_20210910_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='AltPor',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Alterado Por'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='IncPor',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Incluido Por'),
        ),
    ]
