# Generated by Django 3.2.6 on 2021-09-02 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0011_auto_20210901_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_esc_mae',
            field=models.IntegerField(default=1, verbose_name='Escolaridade da Mãe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_esc_pai',
            field=models.IntegerField(default=1, verbose_name='Escolaridade do Pai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='aluno_nome_mae',
            field=models.CharField(default='Maria', max_length=100, verbose_name='Nome da Mãe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_nome_pai',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Pai'),
        ),
    ]
