# Generated by Django 3.2.6 on 2021-09-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0012_auto_20210901_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_dist_escola',
            field=models.IntegerField(choices=[(1, 'Aproximadamente 1km'), (2, 'Aproximadamente 2.5km'), (3, 'Aproximadamente 5km'), (4, 'Aproximadamente 7.5km'), (5, 'Aproximadamente 10km'), (6, 'Aproximadamente 12.5km'), (7, 'Aproximadamente 15km'), (8, 'Aproximadamente 17.5km'), (9, 'Aproximadamente 20km'), (10, 'Aproximadamente 30km'), (11, 'acima de 30km')], default=4, verbose_name='Distância aproximada da residência ao Campus Várzea Grande em KM?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_esc_mae',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação'), (8, 'Mestrado'), (9, 'Doutorado')], verbose_name='Escolaridade da Mãe'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_esc_pai',
            field=models.IntegerField(choices=[(1, 'Ensino Fundamental Incompleto'), (2, 'Ensino Fundamental Completo'), (3, 'Ensino Médio Incompleto'), (4, 'Ensino Médio Completo'), (5, 'Ensino Superior Incompleto'), (6, 'Ensino Superior Completo'), (7, 'Pós-Graduação'), (8, 'Mestrado'), (9, 'Doutorado')], verbose_name='Escolaridade do Pai'),
        ),
    ]
