# Generated by Django 3.2.6 on 2021-09-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0013_auto_20210902_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_agencia',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_conta',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_esc_mae',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_esc_pai',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_nome_mae',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_nome_pai',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_possui_conta',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='aluno_tipo_conta',
        ),
    ]
