# Generated by Django 3.2.6 on 2021-10-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0013_auto_20211002_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_revisar_cadastro',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Forçar o aluno Revisar cadastro?'),
        ),
    ]
