# Generated by Django 3.2.6 on 2021-09-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0014_auto_20210902_0822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='aluno_form_ingre',
            field=models.CharField(choices=[('A', 'Por Ampla Concorrência'), ('C', 'Por Meio de Cota')], max_length=1, verbose_name='Forma de Ingresso'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_matricula',
            field=models.BigIntegerField(unique=True, verbose_name='Matricula'),
        ),
    ]
