# Generated by Django 3.2.6 on 2021-09-02 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20210901_1300'),
        ('aluno', '0015_auto_20210902_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='curso.semestre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='curso.curso'),
            preserve_default=False,
        ),
    ]
