# Generated by Django 3.2.6 on 2021-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0016_auto_20210902_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='aluno_tempo_escola',
            field=models.IntegerField(choices=[(1, 'Aproximadamente 5 minutos'), (2, 'Aproximadamente 10 minutos'), (3, 'Aproximadamente 15 minutos'), (4, 'Aproximadamente 20 minutos'), (5, 'Aproximadamente 25 minutos'), (6, 'Aproximadamente 30 minutos'), (7, 'Aproximadamente 45 minutos'), (8, 'Aproximadamente 1 hora'), (9, 'Aproximadamente 1 hora e 30 minutos'), (10, 'Aproximadamente 2 horas'), (11, 'Acima de 2 horas')], default=1, verbose_name='Tempo que o (a) estudante gasta da sua residência ao Campus'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aluno',
            name='aluno_dist_escola',
            field=models.IntegerField(choices=[(1, 'Aproximadamente 1km'), (2, 'Aproximadamente 2.5km'), (3, 'Aproximadamente 5km'), (4, 'Aproximadamente 7.5km'), (5, 'Aproximadamente 10km'), (6, 'Aproximadamente 12.5km'), (7, 'Aproximadamente 15km'), (8, 'Aproximadamente 17.5km'), (9, 'Aproximadamente 20km'), (10, 'Aproximadamente 30km'), (11, 'acima de 30km')], verbose_name='Distância aproximada da residência ao Campus em KM?'),
        ),
    ]
