# Generated by Django 3.2.6 on 2021-09-02 13:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0019_auto_20210902_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='AltEm',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado Em'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='AltPor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Alterado Por'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='IncEm',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Incluido Em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='IncPor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Incluido Por'),
        ),
    ]
