# Generated by Django 3.2.6 on 2021-09-02 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0020_auto_20210902_0907'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modalidade',
        ),
    ]
