# Generated by Django 3.2.6 on 2021-09-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0022_auto_20210902_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoanexo',
            name='aluno_anexo_valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8, verbose_name='Informe o valor do anexo'),
            preserve_default=False,
        ),
    ]
