# Generated by Django 3.2.6 on 2021-09-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0024_alunoanexo_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoanexo',
            name='aluno_anexo_arq',
            field=models.CharField(default='1', max_length=100, verbose_name='Anexo'),
            preserve_default=False,
        ),
    ]
