# Generated by Django 3.2.6 on 2021-09-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0025_alunoanexo_aluno_anexo_arq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoanexo',
            name='aluno_anexo_arq',
            field=models.CharField(max_length=100, verbose_name='Anexo/Comprovante'),
        ),
    ]
