# Generated by Django 3.2.6 on 2021-09-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='curso_tipo',
            field=models.IntegerField(choices=[(1, 'Técnico'), (2, 'Graduação'), (3, 'Especialização'), (4, 'Mestrado'), (5, 'Doutorado')], default=1, verbose_name='Tipo do Curso'),
            preserve_default=False,
        ),
    ]
