# Generated by Django 3.2.6 on 2021-09-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20210901_1223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='curso',
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_status',
            field=models.BooleanField(default=True, verbose_name='Curso ativo?'),
        ),
        migrations.AlterField(
            model_name='semestre',
            name='semestre_status',
            field=models.BooleanField(default=True, verbose_name='Semestre ativo?'),
        ),
    ]
