# Generated by Django 3.2.6 on 2021-09-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20210901_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='descricao',
        ),
        migrations.AddField(
            model_name='semestre',
            name='curso',
            field=models.ManyToManyField(to='curso.Curso'),
        ),
        migrations.AddField(
            model_name='semestre',
            name='semestre',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre'), (3, '3° Semestre'), (4, '4° Semestre'), (5, '5° Semestre'), (6, '6° Semestre'), (7, '7° Semestre'), (8, '8° Semestre'), (9, '9° Semestre'), (10, '10° Semestre')], default=1, verbose_name='Semestre'),
            preserve_default=False,
        ),
    ]
