# Generated by Django 3.2.6 on 2021-09-01 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20210901_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='curso',
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.ManyToManyField(to='curso.Semestre'),
        ),
    ]
