# Generated by Django 3.2.6 on 2021-09-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('numero', models.PositiveIntegerField(verbose_name='Nº do Edital')),
                ('ano', models.PositiveIntegerField(verbose_name='Informe o ano do Edital')),
                ('data_hora_inicio', models.DateTimeField(null=True, verbose_name='Validade Data/Hora Inicio:')),
                ('data_hora_fim', models.DateTimeField(null=True, verbose_name='Validade Data/Hora Inicio:')),
                ('edital_status', models.BooleanField(default=True, verbose_name='Edital ativo?')),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
        migrations.CreateModel(
            name='PublicacaoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('publicacao_descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('publicacao_anexo_arq', models.CharField(max_length=100)),
                ('publicacao_data', models.DateField(blank=True, null=True, verbose_name='Data da publicação')),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital.edital')),
            ],
            options={
                'verbose_name': 'Publicação',
                'verbose_name_plural': 'Publicações',
            },
        ),
    ]
