# Generated by Django 3.2.6 on 2021-09-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='numero',
            field=models.IntegerField(default=1, max_length=3, verbose_name='Nº do Edital'),
            preserve_default=False,
        ),
    ]
