# Generated by Django 3.2.6 on 2021-09-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0003_edital_modalidade_edital'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetorEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IncPor', models.IntegerField(blank=True, null=True, verbose_name='Incluido Por')),
                ('AltPor', models.IntegerField(blank=True, null=True, verbose_name='Alterado Por')),
                ('IncEm', models.DateTimeField(auto_now_add=True, verbose_name='Incluido Em')),
                ('AltEm', models.DateTimeField(auto_now=True, verbose_name='Alterado Em')),
                ('setor_descricao', models.CharField(max_length=200, verbose_name='Nome do Setor')),
                ('setor_siglas', models.CharField(max_length=20, verbose_name='Sigla do Setor')),
                ('setor_status', models.BooleanField(default=True, verbose_name='Ativo?')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
            },
        ),
        migrations.AlterModelOptions(
            name='modalidadeedital',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': 'Modalidades'},
        ),
    ]
