# Generated by Django 3.2.6 on 2021-09-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0003_alter_edital_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='numero',
        ),
    ]
