# Generated by Django 3.2.6 on 2021-09-02 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0004_auto_20210902_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='setor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edital.setoredital'),
            preserve_default=False,
        ),
    ]
