# Generated by Django 3.2.6 on 2021-09-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0004_remove_edital_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Nº do Edital'),
            preserve_default=False,
        ),
    ]
