# Generated by Django 3.2.6 on 2021-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0005_edital_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='ano',
            field=models.PositiveIntegerField(default=2020, verbose_name='Informe o ano do Edital'),
            preserve_default=False,
        ),
    ]
