# Generated by Django 3.2.6 on 2021-09-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0005_edital_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='titulo',
            field=models.CharField(default='a', max_length=200, verbose_name='Título do Edital'),
            preserve_default=False,
        ),
    ]
