# Generated by Django 3.2.6 on 2021-09-01 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0006_edital_ano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='ano',
        ),
    ]
