# Generated by Django 3.2.6 on 2021-09-02 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0007_auto_20210902_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaoedital',
            name='edital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='edital.edital'),
        ),
    ]
