# Generated by Django 3.2.6 on 2021-09-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0008_edital_ano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='ano',
            field=models.CharField(max_length=20, verbose_name='Informe o ano do Edital'),
        ),
    ]
