# Generated by Django 3.2.6 on 2021-09-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0008_alter_publicacaoedital_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='titulo',
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_descricao',
            field=models.CharField(default='a', max_length=200, verbose_name='Descrição do Edital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_titulo',
            field=models.CharField(default='a', max_length=200, verbose_name='Titulo'),
            preserve_default=False,
        ),
    ]
