# Generated by Django 3.2.6 on 2021-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0009_auto_20210903_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='edital_icone',
            field=models.CharField(choices=[('lni-cog', 'Engrenagem'), ('lni-stats-up', 'Gráfico'), ('lni-users', 'Usuário'), ('lni-layers', 'Design'), ('lni-mobile', 'Mobile'), ('lni-rocket', 'Foguete')], default='a', max_length=20, verbose_name='Icone'),
            preserve_default=False,
        ),
    ]
