# Generated by Django 3.2.6 on 2021-09-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0010_edital_edital_icone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='edital_icone',
        ),
    ]
