# Generated by Django 3.2.6 on 2021-09-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0011_edital_ano'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='data_fim',
            field=models.DateTimeField(null=True, verbose_name='Validade Data/Hora Inicio:'),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_inicio',
            field=models.DateTimeField(null=True, verbose_name='Validade Data/Hora Inicio:'),
        ),
    ]
