# Generated by Django 3.2.6 on 2021-09-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0012_auto_20210901_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='numero',
        ),
    ]
