# Generated by Django 3.2.6 on 2021-09-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0012_edital_semestre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edital',
            old_name='semestre',
            new_name='semestre_edital',
        ),
    ]
