# Generated by Django 3.2.6 on 2021-09-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0013_rename_semestre_edital_semestre_edital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='ano',
            field=models.PositiveIntegerField(verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='data_hora_fim',
            field=models.DateTimeField(null=True, verbose_name='Validade Fim:'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='data_hora_inicio',
            field=models.DateTimeField(null=True, verbose_name='Validade Inicio:'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='edital_descricao',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='edital_titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='semestre_edital',
            field=models.IntegerField(choices=[(1, '1° Semestre'), (2, '2° Semestre')], verbose_name='Semestre'),
        ),
    ]
