# Generated by Django 3.2.6 on 2021-09-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0013_auto_20210901_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='ano',
            field=models.PositiveIntegerField(default=1, verbose_name='Informe o ano do Edital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='data_fim',
            field=models.DateTimeField(null=True, verbose_name='Validade Data/Hora Inicio:'),
        ),
        migrations.AddField(
            model_name='edital',
            name='data_inicio',
            field=models.DateTimeField(null=True, verbose_name='Validade Data/Hora Inicio:'),
        ),
        migrations.AddField(
            model_name='edital',
            name='descricao',
            field=models.CharField(default=1, max_length=100, verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='numero',
            field=models.PositiveIntegerField(default=1, verbose_name='Nº do Edital'),
            preserve_default=False,
        ),
    ]
