# Generated by Django 3.2.6 on 2021-09-28 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0014_auto_20210907_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='edital_quantidade_vaga',
            field=models.IntegerField(default=100, verbose_name='Quantidade de vaga'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_valor_auxilio',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8, verbose_name='Valor do auxílio'),
            preserve_default=False,
        ),
    ]
