# Generated by Django 3.2.6 on 2021-09-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0014_auto_20210901_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='numero',
        ),
    ]
