# Generated by Django 3.2.6 on 2021-10-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0015_auto_20210928_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacaoedital',
            name='publicacao_anexo_arq',
            field=models.FileField(upload_to='media/publicacao', verbose_name='Publicação arquivo'),
        ),
    ]
