# Generated by Django 3.2.6 on 2021-09-02 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0016_edital_numero'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
    ]
