# Generated by Django 3.2.6 on 2021-10-17 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0016_alter_publicacaoedital_publicacao_anexo_arq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edital',
            name='data_hora_fim',
        ),
        migrations.RemoveField(
            model_name='edital',
            name='data_hora_inicio',
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_datetime_correcao_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Final para correção'),
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_datetime_correcao_ini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data Inicio para correção'),
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_datetime_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edital Fechado em:'),
        ),
        migrations.AddField(
            model_name='edital',
            name='edital_datetime_ini',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Edital Aberto em Inicio:'),
        ),
    ]
