# Generated by Django 3.2.6 on 2021-09-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0018_auto_20210902_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='edital',
            name='edital_status',
            field=models.BooleanField(default=True, verbose_name='Edital ativo?'),
        ),
    ]
