# Generated by Django 3.2.6 on 2021-09-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0021_editalanexo_anexo_arq'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EtapaEdital',
            new_name='PublicacaoEdital',
        ),
    ]
