# Generated by Django 3.2.6 on 2021-09-02 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0022_rename_etapaedital_publicacaoedital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editalanexo',
            options={'verbose_name': 'Anexo do Edital', 'verbose_name_plural': 'Anexos do Edital'},
        ),
        migrations.AlterModelOptions(
            name='publicacaoedital',
            options={'verbose_name': 'Publicação', 'verbose_name_plural': 'Publicações'},
        ),
        migrations.RemoveField(
            model_name='editalanexo',
            name='etapa_edital',
        ),
    ]
