# Generated by Django 3.2.6 on 2021-09-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0025_auto_20210902_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacaoedital',
            name='edital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='edital.edital'),
            preserve_default=False,
        ),
    ]
