# Generated by Django 3.2.6 on 2021-09-02 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0026_publicacaoedital_edital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacaoedital',
            old_name='anexo_arq',
            new_name='publicacao_anexo_arq',
        ),
        migrations.RenameField(
            model_name='publicacaoedital',
            old_name='descricao',
            new_name='publicacao_descricao',
        ),
        migrations.AddField(
            model_name='publicacaoedital',
            name='publicacao_data',
            field=models.DateField(blank=True, null=True, verbose_name='Data da publicação'),
        ),
    ]
